# Site settings
title: ThingLearn
email: jen.looper@gmail.com
description: "ThingLearn is a Curriculum. It's a Community. It's also a lot of fun! Let's learn about the Internet of Things together!"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3F95D9
  secondary: FDC004
  secondary-dark: 0B80D9
  link: 3F9F3F
  
# Footer settings
footer:
  copyright: <a href="http://www.ladeezfirstmedia.com">Ladeez First Media</a>
  location: We're local!
  social: Find Us Around the Web
  credits: Built with Love

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jenlooper
  - title: facebook
    url: http://www.facebook.com/thinglearn
  - title: github
    url: http://github.com/jlooper
 
# Postal address (add as many lines as necessary)
address:
  - line: Built in Boston
  
# Credits content
credits: 'A project by <a href="http://www.ladeezfirstmedia.com">Ladeez First Media</a>'

# Build settings
markdown: kramdown
permalink: pretty

#baseurl: /thinglearn
